# Generated by Django 6.1.1 on 2026-09-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=20),
        ),
    ]
